name: Container Job

on:
  push:

jobs:
  container:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/joshjohanning-org/container-job-test:sha256-1d28680218efc92e45f55e2611bad2c5ba2cd11df52b401fe06ce576e7a8ba1f.sig
      credentials:
         username: ${{ github.actor }}
         password: ${{ secrets.ghcr_token }}
    permissions:
      issues: write
      pull-requests: write
      packages: read

    steps:
    - uses: actions/checkout@main
    
