name: Container Job

on:
  push:

jobs:
  container:
    runs-on: self-hosted, azure
    container:
      image: 'ghcr.io/joshjohanning-org/container-job-test:3'
      credentials:
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: actions/checkout@main
    - run: ls
    
