name: Container Job

on:
  push:

jobs:
  container:
    runs-on: ubuntu-latest
    container:
      image: 'ghcr.io/joshjohanning-org/container-job-test:3'
      credentials:
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      issues: write
      pull-requests: write
      packages: read
      contents: read

    steps:
    - uses: actions/checkout@main
    
