name: Container Job

on:
  push:
    branches:
      main

jobs:
  regularjob:
    # runs-on: ubuntu-latest
    runs-on: docker
    steps:
    - run: echo "${{ github.actor }}"
    - name: Code Coverage Summary Report
      uses: irongut/CodeCoverageSummary@v1.2.0
      with:
        filename: coverage/coverage.cobertura.xml
        badge: true
        format: 'markdown'
        output: 'both'
    - run: echo "${{ secrets.TEST_SECRET }}"
    - run: | 
        echo ${{ github.sha }}
        curl -sLX GET https://api.github.com/repos/${{ github.repository}}/commits/${{ github.sha }} \
          --header "Accept: application/vnd.github.v3+json" \
          --header "Authorization: Bearer ${{ secrets.github_token }}" | jq -c '.files[].filename'
    
  container:
    runs-on: [self-hosted, azure]
    # runs-on: ubuntu-latest
    # runs-on: docker
    container:
      # image: 'ubuntu:latest'
      image: 'ghcr.io/joshjohanning-org/container-job-test:17' # 8 works, 9 doesn,t, 3 has USER 1001, 4 does not..
      credentials:
         username: ${{ github.ref }}
         password: ${{ secrets.GITHUB_TOKEN }}
      env: 
        actor: ${{ github.actor }}

    steps:
    - uses: actions/checkout@main
    - run: ls
    - name: test1
      run: |
        echo "$actor"
    - name: test2
      run: echo "${{ github.actor }}"
    - name: test secret
      run: echo "${{ secrets.TEST_SECRET }}"

        
