name: Container Job

on:
  push:

jobs:
  container:
    # runs-on: [self-hosted, azure]
    runs-on: ubuntu-latest
    container:
      # image: 'ubuntu:latest'
      image: 'ghcr.io/joshjohanning-org/container-job-test:13' # 8 works, 9 doesn,t, 3 has USER 1001, 4 does not
      credentials:
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: actions/checkout@main
    - run: ls
    
