name: Docker Image CI

on:
  push:
    branches:
    - main
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  

jobs:
  pre-job:
    outputs:
      pw: ${{ steps.get-pw.outputs.pw }}
    name: other-build
    runs-on: ubuntu-latest
    steps:
      - run: echo "::add-mask::my-password"
      - run: echo "pw=my-password" >> $GITHUB_OUTPUT
        id: get-pw
      
    
  build:
    name: build
    needs: [ pre-job ]
    uses: joshjohanning-org/reusable-workflows/.github/workflows/docker-build.yml@test
    with:
      runs-on: k8s-runner
      image-repository: gh.cr
      image-name: ${{ github.repository }}
      image-tag: ${{ github.run_number }}
      image-pw: ${{needs.pre-job.outputs.pw}}
      dockerfile-path: Dockerfile

