name: Docker Image CI

on:
  push:
    branches:
    - main
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: build
    uses: joshjohanning-org/reusable-workflows/.github/workflows/docker-build.yml@v1.0.0
    with:
      runs-on: k8s-runner
      image-repository: ghcr.io
      image-name: ${{ github.repository }}
      image-tag: ${{ github.run_number }}
      dockerfile-path: Dockerfile

