name: Docker Image CI

on:
  push:
    branches:
    - main
    - multiple-jobs
  pull_request:
    branches: [ main ]
  workflow_dispatch:


jobs:
  docker:
    name: docker
    uses: joshjohanning-org/reusable-workflows/.github/workflows/docker-build.yml@multiple-jobs
    with:
      runs-on: k8s-runner
      image-repository: ghcr.io
      image-name: ${{ github.repository }}
      image-tag: ${{ github.run_number }}
      dockerfile-path: Dockerfile

