name: Docker Image CI

on:
  push:
    branches:
    - main
    - multiple-jobs
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  
env:
  image-repository: ghcr.io

jobs:
  build:
    name: build
    uses: joshjohanning-org/reusable-workflows/.github/workflows/docker-build.yml@multiple-jobs
    with:
      runs-on: k8s-runner
      image-repository: ${{ env.image-repository }}
      image-name: ${{ github.repository }}
      image-tag: ${{ github.run_number }}
      dockerfile-path: Dockerfile

